### ISSUE TITLE
Report  /usr/bin/env failed with exit code 1.

### ISSUE THREAD

**Issue by reback1314** [vknabel/vscode-swiftformat#52] opened 2024-08-30 14:45 UTC
`Error: /usr/bin/env failed with exit code 1.
    at execShellSync (c:\Users\Reback\.vscode\extensions\vknabel.vscode-swiftformat-1.6.10\out\src\execShell.js:13:19)
    at format (c:\Users\Reback\.vscode\extensions\vknabel.vscode-swiftformat-1.6.10\out\src\SwiftFormatEditProvider.js:56:59)
    at SwiftFormatEditProvider.provideDocumentFormattingEdits (c:\Users\Reback\.vscode\extensions\vknabel.vscode-swiftformat-1.6.10\out\src\SwiftFormatEditProvider.js:89:16)
    at W.provideDocumentFormattingEdits (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:154:109715)
    at d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:154:138677
    at De.s (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:154:133052)
    at De.$provideDocumentFormattingEdits (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:154:138664)
    at E.S (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:5980)
    at E.Q (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:5746)
    at E.M (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:4739)
    at E.L (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:3605)
    at i.value (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:2297)
    at n.B (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:737)
    at n.fire (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:954)
    at s.fire (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:14453)
    at i.value (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:177:8655)
    at n.B (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:737)
    at n.fire (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:954)
    at s.fire (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:14453)
    at MessagePortMain.<anonymous> (d:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:177:6781)
    at MessagePortMain.emit (node:events:519:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285)`

**Comment by vknabel** [comment] 2024-11-21 05:59
As I currently neither use Swift nor VS Code, I‘d be happy to receive a PR. Duplicate of #51

**Closed by vknabel** 2024-11-21 05:59 UTC
